services:
  api:
    build:
      context: .
      dockerfile: ./api/Dockerfile
      args:
        NODE_VERSION: 22.13.0
    ports:
      - "3000:3000"
      - "9223:9223"
    environment:
      - DOMAIN=${DOMAIN:-localhost:3000}
      - CDP_DOMAIN=${CDP_DOMAIN:-localhost:9223}
      - CDP_UPSTEAM_URL=${CDP_UPSTEAM_URL:-http://172.17.0.1:8001}
    volumes:
      - ./.cache:/app/.cache
    networks:
      - steel-network
    restart: unless-stopped

  ui:
    build:
      context: .
      dockerfile: ./ui/Dockerfile
      args:
        VITE_AUTOMATION_API_URL: ${VITE_AUTOMATION_API_URL:-http://172.17.0.1:8000}
    ports:
      - "5173:80"
    environment:
      - API_URL=${API_URL:-http://api:3000}
    depends_on:
      - api
    networks:
      - steel-network
    restart: unless-stopped

networks:
  steel-network:
    name: steel-network
    driver: bridge